version: '2.1'
services:

  geoserver:
    image: biggis/geoserver:2.10.4
    hostname: geoserver
    ports:
      - "9090:9090"
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: geoserver
      TOMCAT_ADMIN: biggis
      TOMCAT_ADMIN_PASSWORD: biggis
      TIMEZONE: Europe/Berlin
      CATALINA_HOME: /opt/tomcat
    #volumes:
    #  - geoserver-data:/opt/tomcat/webapps/geoserver/data

#volumes:
#  geoserver-data:
